version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ashback"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1i5dab6yi7c9a"
s3_prefix = "ashback"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
