on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION : "us-east-1" #1

permissions: 
  id-token: write
  contents: read

jobs:
  test-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: test function
        run: python3 -m unittest discover -v hello_world
  build_and_deploy_infra:
    needs: test-infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: aws-actions/setup-sam@v2
#      - uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: us-east-1

      - name: configure aws credentials
#        uses: aws-actions/configure-aws-credentials@v1
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::055359723675:role/OIDC_CRC-Deployment
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}

      # Build inside Docker containers
      - run: sam build
      # Prevent prompts and failure when the stack is unchanged
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset

  deploy_site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: my-fantastic-website123123
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'resume_site'      # optional: defaults to entire repository
